"""MNIST and CIFAR-10 for bias-free MLPs: real data, real depth.

The synthetic tasks establish what the mismatch *is*; these test whether it still governs
training when the targets are not generated by an operator at all. Images are flattened
and the network is a plain bias-free MLP, which is a weak model for CIFAR-10 -- the point
is not accuracy but whether depth remains trainable, so the architecture is held fixed and
depth is the variable.

The wide input layer (784 or 3072 -> width) is beyond any exact per-sample solve, which is
why `OperatorALS` delegates it to an inner optimizer. That split is visible in every run's
metadata rather than buried in the method.
"""
from __future__ import annotations

from pathlib import Path

import torch
import torch.nn.functional as F

from olo.tasks.base import Task

DEFAULT_ROOT = "data"


class _ImageClassification(Task):
    dataset_name: str
    n_classes = 10

    def __init__(
        self,
        root: str = DEFAULT_ROOT,
        batch_size: int = 128,
        n_train: int | None = None,
        n_val: int = 2000,
        n_test: int | None = None,
        seed: int = 0,
        download: bool = True,
    ) -> None:
        from torchvision import datasets, transforms

        tf = transforms.Compose([transforms.ToTensor()])
        ctor = getattr(datasets, self.dataset_name)
        Path(root).mkdir(parents=True, exist_ok=True)
        train = ctor(root=root, train=True, download=download, transform=tf)
        test = ctor(root=root, train=False, download=download, transform=tf)

        # Validation is carved out of the official *train* split; the official test split
        # is touched only by `test()`. Early stopping and lr selection both read
        # validation, so letting them see test would silently turn every reported test
        # number into a selected one.
        want = None if n_train is None else n_train + n_val
        X, y = _stack(train, want)
        g = torch.Generator().manual_seed(seed)
        perm = torch.randperm(X.shape[0], generator=g)
        val_idx, tr_idx = perm[:n_val], perm[n_val:]
        self.Xtr, self.ytr = X[tr_idx], y[tr_idx]
        self.Xva, self.yva = X[val_idx], y[val_idx]
        self.Xte, self.yte = _stack(test, n_test)

        self.d_in = self.Xtr.shape[1]
        self.d_out = self.n_classes
        self.batch_size = int(batch_size)

        # Normalize to zero mean / unit variance per feature, with statistics from the
        # training split only. Depth experiments are sensitive to input scale, and an
        # unnormalized input would confound "this depth is untrainable" with "this input
        # distribution is badly scaled".
        mu = self.Xtr.mean(0, keepdim=True)
        sd = self.Xtr.std(0, keepdim=True).clamp(min=1e-6)
        self.Xtr = (self.Xtr - mu) / sd
        self.Xva = (self.Xva - mu) / sd
        self.Xte = (self.Xte - mu) / sd

        self._perm = torch.randperm(self.Xtr.shape[0], generator=g)

    def to(self, device, dtype):
        for name in ("Xtr", "Xva", "Xte"):
            setattr(self, name, getattr(self, name).to(device=device, dtype=dtype))
        for name in ("ytr", "yva", "yte"):
            setattr(self, name, getattr(self, name).to(device=device))
        return self

    def train_batch(self, step, batch_size=None):
        bs = batch_size or self.batch_size
        n = self.Xtr.shape[0]
        start = (step * bs) % n
        idx = self._perm[torch.arange(start, start + bs) % n]
        return self.Xtr[idx], self.ytr[idx]

    def loss(self, yhat, y):
        return F.cross_entropy(yhat, y)

    def evaluate(self, net) -> dict[str, float]:
        loss, acc = self._score(net, self.Xva, self.yva)
        return {"primary": loss, "val_loss": loss, "val_accuracy": acc}

    def test(self, net) -> dict[str, float]:
        loss, acc = self._score(net, self.Xte, self.yte)
        tr_loss, tr_acc = self._score(net, self.Xtr, self.ytr)
        return {"primary": loss, "test_loss": loss, "test_accuracy": acc,
                "train_loss": tr_loss, "train_accuracy": tr_acc}

    @torch.no_grad()
    def _score(self, net, X, y, chunk: int = 4096) -> tuple[float, float]:
        """Chunked so a full test split does not have to fit in memory at once."""
        total_loss, correct, n = 0.0, 0, X.shape[0]
        for i in range(0, n, chunk):
            logits = net(X[i : i + chunk])
            yb = y[i : i + chunk]
            total_loss += float(F.cross_entropy(logits, yb, reduction="sum"))
            correct += int((logits.argmax(-1) == yb).sum())
        return total_loss / n, correct / n

    def describe(self):
        return {**super().describe(), "dataset": self.dataset_name,
                "n_train": int(self.Xtr.shape[0]), "n_val": int(self.Xva.shape[0]),
                "n_test": int(self.Xte.shape[0]), "batch_size": self.batch_size}


class MNIST(_ImageClassification):
    dataset_name = "MNIST"


class CIFAR10(_ImageClassification):
    dataset_name = "CIFAR10"


def _stack(ds, limit: int | None) -> tuple[torch.Tensor, torch.Tensor]:
    n = len(ds) if limit is None else min(limit, len(ds))
    X = torch.stack([ds[i][0].reshape(-1) for i in range(n)])
    y = torch.tensor([ds[i][1] for i in range(n)], dtype=torch.long)
    return X, y
