"""MNIST and CIFAR-10 for bias-free MLPs: real data, real depth.

The synthetic tasks establish what the mismatch *is*; these test whether it still governs
training when the targets are not generated by an operator at all. Images are flattened
and the network is a plain bias-free MLP, which is a weak model for CIFAR-10 -- the point
is not accuracy but whether depth remains trainable, so the architecture is held fixed and
depth is the variable.

The wide input layer (784 or 3072 -> width) is beyond any exact per-sample solve, which is
why `OperatorALS` delegates it to an inner optimizer. That split is visible in every run's
metadata rather than buried in the method.
"""
from __future__ import annotations

from pathlib import Path

import torch
import torch.nn.functional as F

from olo.tasks.base import Task

DEFAULT_ROOT = "data"


class _ImageClassification(Task):
    dataset_name: str
    n_classes = 10

    def __init__(
        self,
        root: str = DEFAULT_ROOT,
        batch_size: int = 128,
        n_train: int | None = None,
        n_eval: int = 2000,
        seed: int = 0,
        download: bool = True,
    ) -> None:
        from torchvision import datasets, transforms

        tf = transforms.Compose([transforms.ToTensor()])
        ctor = getattr(datasets, self.dataset_name)
        Path(root).mkdir(parents=True, exist_ok=True)
        train = ctor(root=root, train=True, download=download, transform=tf)
        test = ctor(root=root, train=False, download=download, transform=tf)

        self.Xtr, self.ytr = _stack(train, n_train)
        self.Xte, self.yte = _stack(test, n_eval)
        self.d_in = self.Xtr.shape[1]
        self.d_out = self.n_classes
        self.batch_size = int(batch_size)

        # Normalize to zero mean / unit variance per feature. Depth experiments are
        # sensitive to input scale, and an unnormalized input would confound "this depth
        # is untrainable" with "this input distribution is badly scaled".
        mu, sd = self.Xtr.mean(0, keepdim=True), self.Xtr.std(0, keepdim=True).clamp(min=1e-6)
        self.Xtr = (self.Xtr - mu) / sd
        self.Xte = (self.Xte - mu) / sd

        self._perm = torch.randperm(self.Xtr.shape[0], generator=torch.Generator().manual_seed(seed))

    def to(self, device, dtype):
        self.Xtr = self.Xtr.to(device=device, dtype=dtype)
        self.Xte = self.Xte.to(device=device, dtype=dtype)
        self.ytr = self.ytr.to(device=device)
        self.yte = self.yte.to(device=device)
        return self

    def train_batch(self, step, batch_size=None):
        bs = batch_size or self.batch_size
        n = self.Xtr.shape[0]
        start = (step * bs) % n
        idx = self._perm[torch.arange(start, start + bs) % n]
        return self.Xtr[idx], self.ytr[idx]

    def loss(self, yhat, y):
        return F.cross_entropy(yhat, y)

    def evaluate(self, net) -> dict[str, float]:
        with torch.no_grad():
            logits = net(self.Xte)
            loss = float(F.cross_entropy(logits, self.yte))
            acc = float((logits.argmax(-1) == self.yte).to(torch.float64).mean())
        return {"primary": loss, "val_loss": loss, "val_accuracy": acc}

    def describe(self):
        return {**super().describe(), "dataset": self.dataset_name,
                "n_train": int(self.Xtr.shape[0]), "batch_size": self.batch_size}


class MNIST(_ImageClassification):
    dataset_name = "MNIST"


class CIFAR10(_ImageClassification):
    dataset_name = "CIFAR10"


def _stack(ds, limit: int | None) -> tuple[torch.Tensor, torch.Tensor]:
    n = len(ds) if limit is None else min(limit, len(ds))
    X = torch.stack([ds[i][0].reshape(-1) for i in range(n)])
    y = torch.tensor([ds[i][1] for i in range(n)], dtype=torch.long)
    return X, y
